# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(max_length=10000000, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('integrent', models.TextField()),
                ('step', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
