# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20170320_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.CharField(max_length=10000000, primary_key=True, serialize=False),
        ),
    ]
