# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20170326_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='lable',
            field=models.TextField(default='Test default'),
        ),
    ]
